eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8860
spring:
  application:
    name: my-rabbitmq
  rabbitmq:
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual