eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8783
spring:
  application:
    name: my-elastic-job
  datasource:
    url: jdbc:mysql://localhost:3306/my_security?useSSL=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

elasticJob:
  serverLists: 192.168.58.128:8080
  namespace: my-elastic-job
