eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8782
spring:
  application:
    name: my-security-demo
  datasource:
    url: jdbc:mysql://localhost:3306/oeasy_cloud?useSSL=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
#security:
#  user:
#    password: 123456
#    name: 123456

